package com.cyrils.csnewsletter;

import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
public class SubscriptionRequest {
    @JsonProperty("userId")
    private String userID;
    private String email;
    private String topic;

    // Getters and Setters are required for Spring to map the JSON
    // Automatically generated by Lombok
}
